# This is a basic workflow to help you get started with Actions

name: Voting Guide Siesta

# Controls when the action will run. 
on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Configure Git name
        run: git config user.name github-actions
      - name: Configure Git email
        run: git config user.email github-actions@github.com
      - name: Fetch
        run: git fetch
      - name: Check out gh-pages
        run: git checkout gh-pages
      - name: Pull
        run: git pull --rebase
      - name: Copy siesta file to current config
        run: cp config.siesta.json config.json
      - name: Commit change
        run: git commit -am "siesta go to sleep"
      - name: Push
        run: git push

